# Generated by Django 2.2 on 2021-08-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0003_tvshow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
