# Generated by Django 2.2 on 2021-08-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='wall_app.User'),
        ),
    ]
