# Generated by Django 2.2 on 2021-07-31 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dojos', to='dojoNinja_app.Dojo'),
            preserve_default=False,
        ),
    ]
