# Generated by Django 2.2 on 2021-07-31 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinja_app', '0002_ninja_dojo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojos', to='dojoNinja_app.Dojo'),
        ),
    ]
