# Generated by Django 2.2 on 2021-08-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0002_author_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(null=True, related_name='user_favorits', to='dojo_reads_app.User'),
        ),
    ]
