# Generated by Django 2.2 on 2021-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_reads_app', '0003_book_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorited_by',
            field=models.ManyToManyField(related_name='user_favorits', to='dojo_reads_app.User'),
        ),
    ]
