# Generated by Django 2.2 on 2021-07-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
